#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+OPTIONS: author:t broken-links:nil c:nil creator:nil
#+OPTIONS: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:nil
#+OPTIONS: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+OPTIONS: timestamp:t title:t toc:t todo:t |:t
#+TITLE: Daily in His Presence by David Jeremiah - Devotional
#+DATE: <2020-07-20 Mon>
#+AUTHOR: aang
#+EMAIL: aang@aanglap
#+LANGUAGE: es
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 26.3 (Org mode 9.1.9)

*  <2020-07-20 Mon>

  #+BEGIN_VERSE
  Porque tú eres mi roca y mi castillo;
  Por tu nombre me guiarás y me encaminarás.

  - *Salmo 31:3*
  #+END_VERSE
  El general de Northeren Robert McAllister es recordado principalmente por las novecientas cartas que escribió a casa describiendo sus experiencias en la Guerra Civil estadounidense. El 11 de abril de 1864, escribió
  a su esposa, Ellen: "Un día estaba cabalgando para cazar un lugar seguro para disparar a un objetivo. Monté en un pequeño acantilado; y cuando llegué a la cima, escuché una voz. Al mirar hacia abajo en una cantera de piedra vi a dos de nuestros muchachos
  comprometidos fervientemente en la oración, me di la vuelta lo más silenciosamente posible, pensando en lo delicioso que era encontrar un sentimiento tan profundo en mi regimiento ".
  Estamos en una batalla espiritual todos los días, pero nada es más poderoso que una fe que encuentra una cantera de piedra en la que rezar, tal vez con un compañero creyente. La Biblia dice: "/Desde el fin de la tierra, lloraré a Ti, cuando mi corazón
  está abrumado; llévame a la roca que es más alta que yo/".
  


  *Original english version*
  
  #+begin_verse
  For You are my rock and my fortress; therefore, for Your name's sake, lead me and guide me.
  - *Psalm 31:3*
  #+end_verse
  
  Northeren General Robert McAllister is chiefly remembered for the nine hundred letters he wrote home describing his experiences in the American Civil War. On April 11, 1864, he wrote
  his wife, Ellen: "One day I was riding out to hunt a safe place to fire at a target. I rode up on a little bluff; and as I reached the summit, I heard a voice. On looking down into a stone quarry I saw two of our boys
  earnestly engaged in prayer- I turned away as quietly as possible, thinking how delightful it was to find such deep feeling in my regiment."
  We're in a spiritual battle every day, but nothing is more powerful than a quite faith that finds a stone quarry in which to pray, perhaps with a fellow believer. The bible says: "From the end of the earth, I will cry to You, when my heart
  is overwhelmed;  lead me to the rock that is higher than I"
  (Psalm 61:2).


