#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+OPTIONS: author:t broken-links:nil c:nil creator:nil
#+OPTIONS: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:nil
#+OPTIONS: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+OPTIONS: timestamp:t title:t toc:t todo:t |:t
#+TITLE: Daily in His Presence - Devotional by David Jeremiah
#+DATE: <2020-07-20 Mon>
#+AUTHOR: aang
#+EMAIL: aang@aanglap
#+LANGUAGE: es
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 26.3 (Org mode 9.1.9)
#+SETUPFILE: ../org-template/style.org


#+HTML: <hr class="uk-divider-icon">
#+HTML: <article >

*  <2020-07-20 Mon>

  #+BEGIN_VERSE
  Porque tú eres mi roca y mi castillo;
  Por tu nombre me guiarás y me encaminarás.

  - *Salmo 31:3*
  #+END_VERSE
  El general de Northeren Robert McAllister es recordado principalmente por las novecientas cartas que escribió a casa describiendo sus experiencias en la Guerra Civil estadounidense. El 11 de abril de 1864, escribió
  a su esposa, Ellen: "Un día estaba cabalgando para cazar un lugar seguro para disparar a un objetivo. Monté en un pequeño acantilado; y cuando llegué a la cima, escuché una voz. Al mirar hacia abajo en una cantera de piedra vi a dos de nuestros muchachos
  comprometidos fervientemente en la oración, me di la vuelta lo más silenciosamente posible, pensando en lo delicioso que era encontrar un sentimiento tan profundo en mi regimiento ".
  Estamos en una batalla espiritual todos los días, pero nada es más poderoso que una fe que encuentra una cantera de piedra en la cual orar, tal vez con un compañero creyente. La Biblia dice: "/Desde el fin de la tierra, lloraré a Ti, cuando mi corazón
  está abrumado; llévame a la roca que es más alta que yo/".
  


  *Original english version*
  
  #+begin_verse
  For You are my rock and my fortress; therefore, for Your name's sake, lead me and guide me.

  - *Psalm 31:3*
  #+end_verse
  
  Northeren General Robert McAllister is chiefly remembered for the nine hundred letters he wrote home describing his experiences in the American Civil War. On April 11, 1864, he wrote
  his wife, Ellen: "/One day I was riding out to hunt a safe place to fire at a target. I rode up on a little bluff; and as I reached the summit, I heard a voice. On looking down into a stone quarry I saw two of our boys
  earnestly engaged in prayer- I turned away as quietly as possible, thinking how delightful it was to find such deep feeling in my regiment./"
  We're in a spiritual battle every day, but nothing is more powerful than a quite faith that finds a stone quarry in which to pray, perhaps with a fellow believer. The bible says: "/From the end of the earth, I will cry to You, when my heart
  is overwhelmed;  lead me to the rock that is higher than I/"
  (Psalm 61:2).





*  <2020-07-23 Thu> - Tengo Miedo

#+begin_verse
Sé fuerte y de buen valor; no temas ni te desanimes.
- *1 Crónicas 22: 13*
#+end_verse

¿Escuchaste sobre el niño con dos líneas en una obra de teatro? Se suponía que debía decir: "Soy yo. No tengas miedo". Pero cuando subió al escenario, espetó: "Soy yo. ¡Y tengo miedo!" Dios no quiere que pasemos por la vida asustados. Nos da herramientas para vivir con confianza en el mundo. El da su palabra. La Biblia está llena de versículos diseñados para ayudarnos a combatir el miedo y la preocupación personal. Si su mente está ansiosa y temerosa, intente algo como esto. Tome una pila de tarjetas de 3 "x 5" y busque versos de seguridad en la Palabra de Dios. Crea tu propio archivo contra el miedo. Escriba las palabras de la Escritura que más le hablen y manténgalas cerca. Leelos en voz alta. Elija un verso fresco cada día y guárdelo donde pueda verlo. Comience a memorizar los versos uno por uno, compartiéndolos con otros. Oh, sí, podría incluir esta: "Pero inmediatamente Jesús les habló, diciendo:" ¡Anímate! Soy yo; no tengas miedo "(Mateo 14:27).


_*Original english version*_

*I'm Scared*

  #+begin_verse
Be strong and of good courage; do not fear nor be dismayed.

- *1 Chronicles 22:13*
  #+end_verse

Did you hear about the little boy with two lines in a play? He was supposed to say, "It is I. Be not afraid." But when he got on stage, he blurted out, "It's me. And I'm scared!" God doesn't want us to go through life scared. He gives us tools for living confidently in the world. He gives His Word. The Bible is filled with verses designed to assist us in combating personal fear and worry. If your mind is anxious and fearful, try something like this. Grab a stack of 3" x 5" cards and search God's Word for verses of assurance. Create your own anti-fear file. Write down the words of Scripture that speak most to you and keep them close. Read them aloud. Choose a fresh verse each day and keep it where you can see it. Begin memorizing the verses one by one, sharing them with others. Oh, yes-you might include this one: "But immediately Jesus spoke to them, saying, 'Be of good cheer! It is I; do not be afraid" (Matthew 14:27).



*  <2020-07-24 Fri> - Mantenganse firmes

  #+begin_verse
  Hipócritas! Saben cómo discernir la faz del cielo, pero no puedes discernir los signos de los tiempos.  
  - Mateo 16:3
  #+end_verse
  
  Jesús llamó a los líderes religiosos de su época que le pidieron que les mostrara una señal del cielo.  Los reprendió, diciendo que podían leer las señales del clima pero no podían leer las señales de los tiempos (Mateo 16: 1-4).  Eso no fue todo lo que Jesús dijo sobre los signos de los tiempos.  Cuando sus discípulos le preguntaron cuáles serían los signos (indicadores) del fin de la era, les dio muchos (Mateo 24; Lucas 21).  Y el apóstol Pablo le escribió a Timoteo sobre los signos de la impiedad en los últimos días antes del regreso de Cristo: cosas como amar el placer más que amar a Dios y una larga lista de otros (2 Timoteo 3: 1-5).  Dadas las señales que menciona Paul, que tienen que ver con el carácter y el comportamiento personal, el mundo parece encaminado a una crisis descendente.  Mantén tus ojos en la cultura y en Cristo al mismo tiempo.  A medida que el uno se deteriora, la cercanía del Otro aumenta.  Prepárese para mantenerse firme y fiel hasta el final.
  
  *Original english version*
 #+begin_verse
 Hypocrites! You know how to discern the face of the sky, but you cannot discern the signs of the times. 
 
 - *Matthew 16:3*
 #+end_verse

 Jesus called out the religious leaders of His day who asked Him to show them a sign from heaven. He rebuked them, saying they could read the signs of the weather but could not read the signs of the times (Matthew 16:1-4). That wasn't all Jesus said about the signs of the times. When His disciples asked Him what would be the signs (indicators) of the End of the Age, He gave them many (Matthew 24; Luke 21). And the apostle Paul wrote to Timothy about the signs of godlessness in the last days prior to Christ's return-things like loving pleasure more than loving God and a long list of others (2 Timothy 3:1-5). Given the signs that Paul mentions, all of which have to do with personal character and behavior, the world seems headed for a downward crisis. Keep your eyes on the culture and on Christ at the same time. As the one deteriorates, the nearness of the Other increases. Prepare to stand firm and faithful until the end.



#+HTML: </article>
#+INCLUDE: "../disquss.inc"
