#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+OPTIONS: author:t broken-links:nil c:nil creator:nil
#+OPTIONS: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:t
#+OPTIONS: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+OPTIONS: timestamp:t title:t toc:t todo:t |:t
#+TITLE: ¿Qué es la verdad?
#+DATE: <2020-08-07 Fri>
#+AUTHOR: Abel Abner Nolasco Güitian
#+EMAIL: aang.drummer@gmail.com
#+LANGUAGE: es
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 26.3 (Org mode 9.1.9)
#+SETUPFILE: ../org-template/style.org
#+HTML: <hr class="uk-divider-icon">


Dicen que lo mas difícil es comenzar, y creo que es verdad.
Llevo días pensado como reflejar o explicar de la mejor manera parte de lo que hay dentro de mí.
Lo siguiente que voy a escribir será uno de mis intentos por tratar de plasmar mis pensamientos en puño y letra, o en este
caso, en dedo y tecla.


Si es que has leído el título te podrás dar una idea de lo que quiero hablar, de la verdad.
Y quisiera que comenzáramos desde el punto más básico y creo que eso sería definiendo la palabra *verdad*.

** Definición de verdad

   Aquí hay algunas definiciones tomadas de la internet:

   + La verdad es la coincidencia entre una afirmación y los hechos, o la realidad a la que dicha afirmación se refiere o la fidelidad a una idea. [fn:1]
   + La verdad es la correspondencia entre lo que pensamos o sabemos con la realidad. La palabra, como tal, proviene del latín verĭtas, veritātis. [fn:2]
   + La palabra verdad tiene su origen en el latín. Proviene del sustantivo veritas, veritatis que tiene idéntico significado que en español, pero que, además, señala el valor de justicia y rectitud. [fn:3]
     
     
   Los cristianos dicen tener la verdad, los musulmanes o islamicos o cualquiera de los demás sin fin de grupos religiosos. ¿Quién realmente tiene la verdad?.
   
   Definitivamente esa palabra '*Verdad*' tiene un gran peso en nuestra actualidad.
   

  
** Algunos ejemplos de hombres que tuvieron un cambio radical en su vida


   - Sandhu Sundar Singh https://es.wikipedia.org/wiki/Sandhu_Sundar_Singh
   - Robert Murray M'Cheyne https://es.wikipedia.org/wiki/Robert_Murray_M%27Cheyne

** Resumen muy general

   Nosotros tenemos luz porque Él nos ha alumbrado. Y si él nos ha alumbrado entonces ese alumbramiento tiene que reflejar algo, su esencia.


** Algunos cuestionamientos

   Haz click en el siguiente enlace para ver el documento en pdf:
   [[../files/analisis.pdf][Documento en pdf.]]

** Conclusión

   #+BEGIN_VERSE
   /Lo que pido de ustedes es amor y no sacrificios, conocimiento de Dios y no holocaustos./ 
   - *Oseas 6:6*
   #+END_VERSE
   
* Footnotes

[fn:3] http://playersbehindthescreen.blogspot.com/2015/10/que-es-la-verdad-en-vocablo-griego.html
[fn:2] https://www.significados.com/verdad/
[fn:1] https://es.wikipedia.org/wiki/Verdad
   
   
   
