#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+OPTIONS: author:t broken-links:nil c:nil creator:nil
#+OPTIONS: d:(not "LOGBOOK") date:t e:t email:nil f:nil inline:t num:nil
#+OPTIONS: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+OPTIONS: timestamp:t title:t toc:t todo:t |:t
#+TITLE: ¿Qué es la verdad?
#+DATE: <2020-08-07 Fri>
#+AUTHOR: Abel Abner Nolasco Güitian
#+EMAIL: aang.drummer@gmail.com
#+LANGUAGE: es
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 26.3 (Org mode 9.1.9)
#+SETUPFILE: ../org-template/style.org
#+HTML: <hr class="uk-divider-icon">
#+HTML: <div>

* Intro

Dicen que lo mas difícil es comenzar, y creo que es verdad.
Llevo días pensado como reflejar o explicar de la mejor manera parte de lo que hay dentro de mí.
Lo siguiente que voy a escribir será uno de mis intentos por tratar de plasmar mis pensamientos en puño y letra, o en este
caso, en dedo y tecla.


Si has leído el título te podrás dar una idea de lo que quiero hablar, /de la verdad/.
Y quisiera que comenzáramos desde el punto más básico, definir la palabra *verdad*.

* Definición de verdad

  Podemos obtener algunas definiciones de la internet:

  + La verdad es la coincidencia entre una afirmación y los hechos, o la realidad a la que dicha afirmación se refiere o la fidelidad a una idea. El término se usa en un sentido técnico en diversos campos como la ciencia, la lógica, las matemáticas y la filosofía.  También el acuerdo de los conocimientos con las cosas que se afirman como realidades: los hechos o la cosa en particular; y, finalmente, la relación de los hechos o las cosas en su totalidad en la constitución del Todo, el Universo. [fn:1]
  + La verdad es la correspondencia entre lo que pensamos o sabemos con la realidad. La palabra, como tal, proviene del latín verĭtas, veritātis. [fn:2]
          
  # Los cristianos dicen tener la verdad, los musulmanes o islamicos o cualquiera de los demás sin fin de grupos religiosos. ¿Quién realmente tiene la verdad?.
  En conclusión podemos decir que la verdad es la relación de igualdad respecto a lo que decimos y/o pensamos con los hechos (realidad).
  La verdad es inalterable, no esta sujeta a relativismos, es simplemente lo que es y ya.
   
  Definitivamente esa palabra _'*verdad*'_ remarca un significado absoluto, una realidad y es imprescindible (o debería serlo) para cada ser humano en este planeta.

* Alguien que dijo ser la verdad misma

  A lo largo de la historia hemos visto de todo, hombres que trataron de conquistar el mundo, hombres que se llamaban o creían /dioses/, hasta historias acerca de otros mil dioses mas.
  Pero hay algo que dijo un tal Jesús de Nazaret, que es lo voy a tratar de abordar, analizando la historia y el libro que habla acerca de Él, la Biblia.

  Conocido en el occidente como /Jesús/ y en el original /Yeshúa/ fue el judío que expresó lo que ha sido sencillamente lo mas impresionante que ha hablado un ser humano.
  Él dijo que Él es uno con Dios, que nadie puede llegar a ese Dios si no solamente a través de Él.
  Ahora bien, ¿Qué Dios?, si en el mundo han aparecido muchos "dioses". Bien pues hablamos del Dios de los judíos, o más precisamente del pueblo de Israel, tal como lo dicen las Escrituras.
  El Dios que se dice que creó el cosmos, el cielo, la tierra y todo lo que en ello hay.

  C.S. Lewis lo explicó de la siguiente manera:
   
  #+begin_verse
     Dios, en el lenguaje de los, judíos, significaba el Ser aparte del mundo que Él había creado y que era infinitamente diferente de todo lo demás.
  #+end_verse
   
  Cuando escriba *Dios*, a ese /Dios/ me estaré refiriendo. De echo tiene su propio nombre (más adelante veremos cual es).

* Definición de verdad según las Escrituras

  Hemos visto la definición del concepto de _verdad_ de acuerdo a algunos diccionarios encontrados en la web, pero no de acuerdo a nuestro punto de referencia 
  principal en nuestro intento de estudiar, lo que ese *Dios* de los judíos dejó escrito, hablamos de lo que comúnmente se conoce como la /[[https://es.wikipedia.org/wiki/Biblia][Biblia]]/.
  Cuando hago mención de la palabra _*Escrituras*_ me estoy refiriendo precisamente a eso (la biblia).




   #+HTML: </div>
   #+INCLUDE: "../disquss.inc"


* Footnotes :noexport:

[fn:2] https://www.significados.com/verdad/
[fn:1] https://es.wikipedia.org/wiki/Verdad


** Algunos ejemplos de hombres que tuvieron un cambio radical en su vida :noexport:


   - Sandhu Sundar Singh https://es.wikipedia.org/wiki/Sandhu_Sundar_Singh
   - Robert Murray M'Cheyne https://es.wikipedia.org/wiki/Robert_Murray_M%27Cheyne

     
** Resumen muy general :noexport:

   Nosotros tenemos luz porque Él nos ha alumbrado. Y si él nos ha alumbrado entonces ese alumbramiento tiene que reflejar algo, su esencia.

   
** Algunos cuestionamientos :noexport:
   
   Haz click en el siguiente enlace para ver el documento en pdf:
   [[../files/analisis.pdf][Documento en pdf.]]


** Conclusión :noexport:

   #+BEGIN_VERSE
   /Lo que pido de ustedes es amor y no sacrificios, conocimiento de Dios y no holocaustos./ 
   - *Oseas 6:6*
   #+END_VERSE









