#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+OPTIONS: author:t broken-links:nil c:nil creator:nil
#+OPTIONS: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:nil
#+OPTIONS: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+OPTIONS: timestamp:t title:t toc:t todo:t |:t
#+TITLE: ¿Qué es la verdad?
#+DATE: <2020-08-07 Fri>
#+AUTHOR: Abel Abner Nolasco Güitian
#+EMAIL: aang.drummer@gmail.com
#+LANGUAGE: es
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 26.3 (Org mode 9.1.9)
#+SETUPFILE: ../org-template/style.org
#+HTML: <hr class="uk-divider-icon">


Dicen que lo mas difícil es comenzar, y creo que es verdad.
Llevo días pensado como reflejar o explicar de la mejor manera parte de lo que hay dentro de mí.
Lo siguiente que voy a escribir será uno de mis intentos por tratar de plasmar mis pensamientos en puño y letra, o en este
caso, en dedo y tecla.


Si has leído el título te podrás dar una idea de lo que quiero hablar, /de la verdad/.
Y quisiera que comenzáramos desde el punto más básico, definir la palabra *verdad*.

** Definición de verdad

   Podemos obtener algunas definiciones de la internet:

   + La verdad es la coincidencia entre una afirmación y los hechos, o la realidad a la que dicha afirmación se refiere o la fidelidad a una idea. El término se usa en un sentido técnico en diversos campos como la ciencia, la lógica, las matemáticas y la filosofía.  También el acuerdo de los conocimientos con las cosas que se afirman como realidades: los hechos o la cosa en particular; y, finalmente, la relación de los hechos o las cosas en su totalidad en la constitución del Todo, el Universo. [fn:1]
   + La verdad es la correspondencia entre lo que pensamos o sabemos con la realidad. La palabra, como tal, proviene del latín verĭtas, veritātis. [fn:2]
          
   # Los cristianos dicen tener la verdad, los musulmanes o islamicos o cualquiera de los demás sin fin de grupos religiosos. ¿Quién realmente tiene la verdad?.
   En conclusión podemos decir que la verdad es la relación de igualdad respecto a lo que decimos y/o pensamos con los hechos (realidad).
   Por lo tanto podemos decir que la verdad no es dependiente de la subjetividad o relativismo, es absoluta.
   
   Definitivamente esa palabra _'*verdad*'_ remarca un significado absoluto, una realidad y es imprescindible (o debería serlo) para cada ser humano en este planeta llamado _tierra_.
   

  
** Algunos ejemplos de hombres que tuvieron un cambio radical en su vida :noexport:


   - Sandhu Sundar Singh https://es.wikipedia.org/wiki/Sandhu_Sundar_Singh
   - Robert Murray M'Cheyne https://es.wikipedia.org/wiki/Robert_Murray_M%27Cheyne


** Resumen muy general :noexport:

   Nosotros tenemos luz porque Él nos ha alumbrado. Y si él nos ha alumbrado entonces ese alumbramiento tiene que reflejar algo, su esencia.

   
** Algunos cuestionamientos
   
   Haz click en el siguiente enlace para ver el documento en pdf:
   [[../files/analisis.pdf][Documento en pdf.]]


** Conclusión

   #+BEGIN_VERSE
   /Lo que pido de ustedes es amor y no sacrificios, conocimiento de Dios y no holocaustos./ 
   - *Oseas 6:6*
   #+END_VERSE


   
* Footnotes


[fn:2] https://www.significados.com/verdad/
[fn:1] https://es.wikipedia.org/wiki/Verdad
   
   
   
